const express=require('express'),http=require('http'),{WebSocketServer}=require('ws'),{Pool}=require('pg'),path=require('path');
const app=express(),server=http.createServer(app),wss=new WebSocketServer({server});
const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.NODE_ENV==='production'?{rejectUnauthorized:false}:false});
const rooms=new Map(); app.use(express.static(path.join(__dirname,'public')));
const send=(w,x)=>w.readyState===1&&w.send(JSON.stringify(x));
async function db(){await pool.query(`CREATE TABLE IF NOT EXISTS players(id TEXT PRIMARY KEY,nickname TEXT NOT NULL DEFAULT 'Гравець',avatar TEXT,wins INT NOT NULL DEFAULT 0,updated_at TIMESTAMPTZ DEFAULT NOW())`)}
async function get(id){let r=await pool.query('SELECT * FROM players WHERE id=$1',[id]);if(r.rows[0])return r.rows[0];return (await pool.query('INSERT INTO players(id) VALUES($1) RETURNING *',[id])).rows[0]}
const rank=w=>w>=100?'👑 Легенда':w>=80?'💎 Діамант 1':w>=60?'💎 Діамант 2':w>=45?'💎 Діамант 3':w>=35?'🥇 Золото 1':w>=27?'🥇 Золото 2':w>=20?'🥇 Золото 3':w>=15?'🥈 Срібло 1':w>=10?'🥈 Срібло 2':w>=6?'🥈 Срібло 3':w>=4?'🥉 Бронза 1':w>=2?'🥉 Бронза 2':'🥉 Бронза 3';
function win(b,n){let need=n===3?3:n===4?4:5,d=[[1,0],[0,1],[1,1],[1,-1]];for(let r=0;r<n;r++)for(let c=0;c<n;c++){let v=b[r*n+c];if(!v)continue;for(let [dr,dc] of d){let ok=1;for(let k=1;k<need;k++){let rr=r+dr*k,cc=c+dc*k;if(rr<0||rr>=n||cc<0||cc>=n||b[rr*n+cc]!==v){ok=0;break}}if(ok)return v}}return b.every(Boolean)?'draw':null}
function state(r){return {type:'state',name:r.name,size:r.size,board:r.board,turn:r.turn,result:r.result,players:r.players.map(p=>({id:p.id,mark:p.mark,nickname:p.nickname,avatar:p.avatar,wins:p.wins,rank:rank(p.wins)}))}}
function broadcast(r){let s=state(r);r.players.forEach(p=>send(p.ws,s))}
wss.on('connection',ws=>{ws.on('message',async raw=>{let m;try{m=JSON.parse(raw)}catch{return} ;if(m.type==='profile'){let p=await get(m.id);p=(await pool.query('UPDATE players SET nickname=$1,avatar=$2,updated_at=NOW() WHERE id=$3 RETURNING *',[String(m.nickname||'Гравець').slice(0,24),m.avatar||p.avatar,m.id])).rows[0];return send(ws,{type:'profile',player:{...p,rank:rank(p.wins)}})}
if(m.type==='leaderboard'){let top=(await pool.query('SELECT * FROM players ORDER BY wins DESC,updated_at ASC LIMIT 100')).rows,me=await get(m.id),pos=(await pool.query('SELECT COUNT(*)+1 AS n FROM players WHERE wins>$1',[me.wins])).rows[0].n;return send(ws,{type:'leaderboard',top:top.map((p,i)=>({...p,position:i+1,rank:rank(p.wins)})),me:{...me,position:+pos,rank:rank(me.wins)}})}
if(m.type==='servers')return send(ws,{type:'servers',servers:[...rooms.values()].filter(r=>r.public&&r.players.length<2).map(r=>({id:r.id,name:r.name,size:r.size,host:r.players[0]?.nickname||'Гравець'}))});
if(m.type==='create'){let p=await get(m.id),id=Math.random().toString(36).slice(2,8).toUpperCase(),size=Math.max(3,Math.min(8,+m.size||3)),r={id,name:String(m.name||'Мій сервер').slice(0,30),size,public:!!m.public,board:Array(size*size).fill(''),turn:'X',result:null,players:[]};rooms.set(id,r);r.players.push({...p,ws,mark:'X'});ws.room=id;ws.mark='X';ws.id=m.id;send(ws,{type:'joined',room:id,private:!r.public});broadcast(r);return}
if(m.type==='join'){let r=rooms.get(String(m.room||'').toUpperCase());if(!r)return send(ws,{type:'error',message:'Сервер не знайдено.'});if(r.players.length>=2)return send(ws,{type:'error',message:'Сервер уже заповнений.'});let p=await get(m.id);r.players.push({...p,ws,mark:'O'});ws.room=r.id;ws.mark='O';ws.id=m.id;send(ws,{type:'joined',room:r.id,private:!r.public});broadcast(r);return}
let r=rooms.get(ws.room);if(!r)return;if(m.type==='move'){let i=+m.index;if(r.result||r.players.length<2||ws.mark!==r.turn||!Number.isInteger(i)||i<0||i>=r.board.length||r.board[i])return;r.board[i]=ws.mark;r.result=win(r.board,r.size);if(r.result&&r.result!=='draw'){let p=r.players.find(x=>x.mark===r.result),q=(await pool.query('UPDATE players SET wins=wins+1,updated_at=NOW() WHERE id=$1 RETURNING *',[p.id])).rows[0];p.wins=q.wins}else if(!r.result)r.turn=r.turn==='X'?'O':'X';broadcast(r)}
if(m.type==='restart'){r.board.fill('');r.turn='X';r.result=null;broadcast(r)} if(m.type==='leave'){r.players=r.players.filter(p=>p.ws!==ws);if(!r.players.length||!r.public)rooms.delete(r.id);else broadcast(r)}});ws.on('close',()=>{let r=rooms.get(ws.room);if(!r)return;r.players=r.players.filter(p=>p.ws!==ws);if(!r.players.length||!r.public)rooms.delete(r.id);else broadcast(r)})});
db().then(()=>server.listen(process.env.PORT||3000,'0.0.0.0',()=>console.log('online'))).catch(e=>{console.error(e);process.exit(1)});
